# config.yaml

paths:
  train_data: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/Datasets/Raw/train.csv
  test_data: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/Datasets/Raw/test.csv
  store_data: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/Datasets/Raw/store.csv
  test_store_data: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/Datasets/clean/test_store_data.csv
  train_store_data:  /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/Datasets/clean/train_store_data.csv
  predictions_data: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/Datasets/Prediction/predictions_historical.csv

settings:
  model_output: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/trained_xgb_model.pkl
  functions.py: /Users/mustafaaldabbas/Documents/GitHub/Rossmann-sales-prediction/functions.py